# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5683f1c6f7d96655f44824596125b904"
name = "plixxo-app"
application_url = "https://oriental-binary-maine-toys.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[app_proxy]
url = "https://oriental-binary-maine-toys.trycloudflare.com/cartApi"
subpath = "cartApi"
prefix = "apps"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products , write_files , write_app_proxy , read_publications , read_locations , write_inventory , read_inventory , write_publications"

[auth]
redirect_urls = [ "https://oriental-binary-maine-toys.trycloudflare.com/api/auth" ]
