# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9128d76120b8ad8d446aa649d25dbe12"
name = "Kellerfensteronline-App"
application_url = "https://goldfish-app-v96wu.ondigitalocean.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[app_proxy]
url = "https://goldfish-app-v96wu.ondigitalocean.app/cartApi"
subpath = "cartApi"
prefix = "apps"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products , write_files , write_app_proxy , read_publications , read_locations , write_inventory , read_inventory , write_publications"

[auth]
redirect_urls = [ "https://goldfish-app-v96wu.ondigitalocean.app/api/auth" ]
